sudo: required
language: php
php:
  - 7.4
services:
  - docker

dist: bionic
# add this to resolve docker building error for travis ci
# error: ls: cannot access '.': Operation not permitted

before_install:
  - docker build -t ally/booknotes -f Dockerfile ./

before_script:
#  - php composer.phar install
  - composer require --dev phpunit/phpunit ^9.5

script: vendor/bin/phpunit ./tests

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "dockerized-booknotes"
  env: "Dockerizedbooknotes-env"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY