version: '3.7'
services:
  database:
    image: mysql:5.6
    env_file:
      - .env
    volumes:
      - db-datavolume:/var/lib/mysql
  web:
    build: .
    depends_on:
      - database
    ports:
      - "3000:80"
    volumes:
      - ./:/usr/src/BookNotes
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
# create docker volume on the host machine and attach to the database container
volumes:
  db-datavolume: #to add
    driver: local
    